### ISSUE TITLE
Fixing minor typos in training1

### ISSUE THREAD

**Issue by ermyas** [ConsenSys/dafny-training#1]
Thanks again for putting this great course together. I came across a couple of very minor typos on the first training module that I wanted to confirm with you first before submitting a PR that addresses them:

- In the code snippet for calculating `max()` below, do we mean to assign `r` to `x` and `y` instead of `0` and `1`? or is that part of the exercise? The comments don't seem to suggest it is. 
https://github.com/ConsenSys/dafny-training/blob/80ca1ada297a68732ad8c36684e8fee42390c21b/session1/training1.dfy#L51-L55

- The comment in the snippet below notes `a[i..]` is the same as `a[i..|a|-1]`, should this be `a[i..|a|]` instead? 
https://github.com/ConsenSys/dafny-training/blob/80ca1ada297a68732ad8c36684e8fee42390c21b/session1/training1.dfy#L120

- (similar to above), the snippet below notes `a[0..|a|-1]` is the same as `a` ... should that be `a[0..|a|]` instead? 
https://github.com/ConsenSys/dafny-training/blob/80ca1ada297a68732ad8c36684e8fee42390c21b/session1/training1.dfy#L155

- In the comment below the line number appears slightly incorrect and the mentioned code does not seem to match what is currently commented. Should it either refer to line 131 and the code `index:=index + 1` or should it refer to line 135, and that code instead be commented out? 
https://github.com/ConsenSys/dafny-training/blob/80ca1ada297a68732ad8c36684e8fee42390c21b/session1/training1.dfy#L110

- In the below, segments should the comment read `element k of a...`
https://github.com/ConsenSys/dafny-training/blob/80ca1ada297a68732ad8c36684e8fee42390c21b/session1/training1.dfy#L153
https://github.com/ConsenSys/dafny-training/blob/80ca1ada297a68732ad8c36684e8fee42390c21b/session1/training1.dfy#L183

- should this statement be changed to a `decreases *` as the comment in [line 66](https://github.com/ConsenSys/dafny-training/blob/80ca1ada297a68732ad8c36684e8fee42390c21b/session1/training1.dfy#L66) notes? gives too much of a hint otherwise :D
https://github.com/ConsenSys/dafny-training/blob/80ca1ada297a68732ad8c36684e8fee42390c21b/session1/training1.dfy#L75

**Comment by franck44** [comment]
@ermyas Thanks for that. I have (hopefully) fixed the problems.
